version: '3'

services:
  hotel-app:
    container_name: hotel-app
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        CLERK_SECRET_KEY: ${CLERK_SECRET_KEY}
        NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
    restart: unless-stopped
    ports:
      - 3000:3000
