import type { Metadata } from 'next'
import { Inter as FontSans } from 'next/font/google'
import './styles/globals.css'
import { cn } from '@/lib/utils'
import StoreProvider from './StoreProvider'
import ReactQueryProvider from '../providers/ReactQueryProvider'
import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs'

const fontSans = FontSans({
  subsets: ['latin'],
  variable: '--font-sans',
})

export const metadata: Metadata = {
  title: 'Hotel App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <head />
        <body
          className={cn(
            'min-h-screen bg-background font-sans antialiased',
            fontSans.variable
          )}
          suppressHydrationWarning
        >
          <ReactQueryProvider>
            <StoreProvider>{children}</StoreProvider>
          </ReactQueryProvider>
        </body>
      </html>
    </ClerkProvider>
  )
}
